[package]
name = "spruce2"
version = "0.1.0"
authors = ["jesserwight <jessewright01@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.2.0"
askama = "0.10.3"
serde = "1.0.117"
env_logger = "0.8.1"
validator = { version = "0.11.0", features = ["derive"] }
serde_json = "1.0.59"
sqlx = { version = "0.4.0", features = ["postgres", "macros", "chrono", "runtime-actix-native-tls"] }
dotenv = "0.15.0"
actix-multipart = "0.3.0"
futures = "0.3.8"
sanitize-filename = "0.3.0"
