[package]
name = "spruce2"
version = "0.1.0"
authors = ["jesserwight <jessewright01@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.1.0"
askama = "0.10.3"
serde = "1.0.117"
env_logger = "0.8.1"
validator = { version = "0.11", features = ["derive"] }
