services:
  db:
    image: postgres:alpine
    restart: always
    ports: 
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass

  web:
    image: howido-build
    environment:
      PORT: 80
      DATABASE_URI: postgresql://postgres:pass@db:5432/postgres
    ports: 
      - "80:80"
    depends_on:
      - db

volumes:
  db_data: {}
